version: '3.9'

services:
  api-helpup-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=felipe
      - POSTGRESQL_PASSWORD=helpuppass
      - POSTGRESQL_DATABASE=helpup
    container_name: db_helpup
    volumes:
      - pgdata:/data/postgres
    hostname: db_helpup

volumes:
  pgdata:
    driver: local
