version: '3.9'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=dockerpass
      - POSTGRESQL_DATABASE=apisolid
    container_name: db_apisolid
    volumes:
      - pgdata:/data/postgres
    networks:
      - apisolid_network
    hostname: db_solidapi

  app:
    build: .
    container_name: app_apisolid
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - apisolid_network
    environment:
      - DATABASE_URL=postgres://docker:dockerpass@db_solidapi:5432/apisolid
      - NODE_ENV=dev

volumes:
  pgdata:
    driver: local

networks:
  apisolid_network:
    driver: bridge
