version: '3.9'

services:
  app:
    build: .
    container_name: app_apisolid
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    environment:
      - DATABASE_URL=postgres://felipe:helpuppass@db_helpup:5432/helpup
      - NODE_ENV=production
      - PORT=3333

volumes:
  pgdata:
    driver: local