name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd var/www/server-helpup
            git checkout .
            git pull origin main
            npx prisma migrate deploy
            docker-compose up -d --build
            docker image prune -a --filter "until=10m" --force
            docker container prune -f
            docker volume prune -f
