name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into Digital Ocean and Execute Commands
        run: |
          ssh root@157.230.200.236 "cd server-helpup && yarn build && yarn start && p2m restart server"
