name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn run test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: run-unit-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/server-helpup
            git pull origin main
            yarn build
            docker-compose down
            docker-compose up -d --build
