name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: 'yarn'

      - name: Create .env file
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "LOGO_URL=${{ secrets.LOGO_URL }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "CONFIRM_MAIL_URL=${{ secrets.CONFIRM_MAIL_URL }}" >> .env
          echo "MAIL_HOST=${{ secrets.MAIL_HOST }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_USER=${{ secrets.MAIL_USER }}" >> .env
          echo "MAIL_PASS=${{ secrets.MAIL_PASS }}" >> .env

      - run: yarn install --frozen-lockfile
      - run: yarn run test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: run-unit-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/server-helpup
            git pull origin main
            yarn build
            docker-compose down
            docker-compose up -d --build
