name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Create SSH key
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private.key
          sudo chmod 400 private.key

      - name: SSH into Digital Ocean and Execute Commands
        run: |
          ssh root@157.230.200.236 "cd server-helpup && yarn build && yarn start && p2m restart server"
