name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.0
          cache: 'yarn'

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Construir projeto
        run: yarn build

      - name: Parar o PM2
        run: pm2 stop server || true

      - name: Iniciar o PM2
        run: pm2 start build/server.js
