name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Deploy on digital ocean
        run: |
          echo '$SSH_PRIVATE_KEY' > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key root@157.230.200.236 "cd server-helpup && git pull origin main && yarn build && p2m restart server"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
