name: Deploy app

on:
  push:
    branches:
      - main

jobs:
  run-deploy:
    name: Deploy server
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: 'yarn'

      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Construir projeto
        run: yarn build

      - name: Parar o PM2
        run: pm2 stop server || true

      - name: Iniciar o PM2
        run: pm2 start build/server.js
